version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: circleci/node:10.19.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}

workflows:
  deploy_to_develop:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - heroku/deploy-via-git:
          app-name: ${HEROKU_APP_NAME_DEVELOP}
          requires:
            - build
          filters:
            branches:
              only:
                - develop
  deploy_to_staging:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - heroku/deploy-via-git:
          app-name: ${HEROKU_APP_NAME_STAGING}
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  deploy_to_production:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - heroku/deploy-via-git:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
